server:
  port: 8082

spring:
  profiles:
    active: dev
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: "http://localhost:8888"

  application:
    name: inventory-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8090/realms/InovSmart}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8090/realms/InovSmart/protocol/openid-connect/certs}

